version: "3.9"

services:
  db:
    container_name: db
    image: postgres:14-alpine3.16
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5437:5432"
    networks:
      - db-network

  api:
    build: .
    container_name: api
    command: sh -c "python fastapi_template/main.py"
    environment:
      - PATH=/directory/bin:$PATH
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
