name: FastAPI CI/CD

on:
  # Allows you to call this workflow within another workflow
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggered based on the git event type
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  flake8:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Lint with flake8
        run: |
          pip install flake8 flake8-html
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          mkdir -p reports/flake8
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics --format=html --htmldir=reports/flake8
      - name: Archive flake8 coverage results
        uses: actions/upload-artifact@v1
        with:
          name: flake8-coverage-report
          path: reports/flake8/

  pytest:
    name: Unit Testing
    needs: flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          poetry install
      - name: Test with pytest
        run: |
          poetry run pip install pytest pytest-cov pytest-html pytest-sugar pytest-json-report pytest-asyncio
          poetry run coverage run --concurrency=greenlet tests --test
      - name: Archive pytest coverage results
        uses: actions/upload-artifact@v1
        with:
          name: pytest-coverage-report
          path: reports/pytest/
